server:
  port: 8080
  servlet:
    contextPath: /ms-rolespermisos
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
      

      
  main:
    allow-circular-references: true
    
  
        
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
            
logging:
  level:
    root: info
    org.springframework.web: info
    org.hibernate: error

logos:
  msit_logo_imss: /sintrans_data/LOGOS/logoImss.png
  msit_logo_sistema: /sintrans_data/LOGOS/logoSistema.png

endpoints:
   dominio-consulta: http://localhost:8094/mssivimss-mod-catalogos
   consulta-generica : http://localhost:8094/mssivimss-mod-catalogos/generico/consulta
   consulta-generica-paginado: http://localhost:8094/mssivimss-mod-catalogos/generico/paginado
   guardar-datos: http://localhost:8094/mssivimss-mod-catalogos/generico/crear
   actualizar-datos: http://localhost:8094/mssivimss-mod-catalogos/generico/actualizar

jwt:
  secretkey-rolespermisos: funcionamuybien
  secretkey-dominios: funcionamuybiendominio
  expiration-milliseconds: 360